namespace TwitchLib.Api.Core.Enums
{
    public enum AuthScopes
    {
        Any,
        Channel_Check_Subscription,
        Channel_Commercial,
        Channel_Editor,
        Channel_Feed_Edit,
        Channel_Feed_Read,
        Channel_Read,
        Channel_Stream,
        Channel_Subscriptions,
        Chat_Login,
        Collections_Edit,
        Communities_Edit,
        Communities_Moderate,
        User_Blocks_Edit,
        User_Blocks_Read,
        User_Follows_Edit,
        User_Read,
        User_Subscriptions,
        Viewing_Activity_Read,
        OpenId,
        Helix_User_Edit,
        Helix_User_Read_Email,
        Helix_Clips_Edit,
        Helix_Bits_Read,
        Helix_Analytics_Read_Games,
        Helix_Analytics_Read_Extensions,
        Helix_User_Edit_Broadcast,
        Helix_User_Read_Broadcast,
        None
    }
}
